name: Say Hello

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello in terminal
        run: echo "👋 Hello from GitHub Actions!"
